spring:
  profiles:
    active: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#    converters:
#      preferred-json-mapper: gson
  resources:
    chain:
      compressed: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB
      file-size-threshold: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
server:
  compression:
    enabled: true
  error:
    path: /common/exception/error
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_MYAPP
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: shutdown, health
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
---
spring:
  profiles: local
  datasource:
    initialization-mode: always
    schema: classpath:/removabledb/schema.sql
    data: classpath:/removabledb/data.sql
    sql-script-encoding: UTF-8
server:
  port: 8080
variable:
  app:
    title: My SpringBoot + JPA + VueJs + Typescript
---
spring:
  profiles: dev
  datasource:
    hikari:
      username:
      password:
      driver-class-name: org.jdbcdslog.DriverLoggingProxy
      jdbc-url: jdbc:jdbcdslog:mysql://127.0.0.1:3306/dbname?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull;targetDriver=org.gjt.mm.mysql.Driver
server:
  port: 3401
variable:
  app:
    title:
---
spring:
  profiles: production
  datasource:
    hikari:
      username:
      password:
      driver-class-name: org.jdbcdslog.DriverLoggingProxy
      jdbc-url: jdbc:jdbcdslog:mysql://127.0.0.1:3306/dbname?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull;targetDriver=org.gjt.mm.mysql.Driver
server:
  port:
variable:
  app:
    title:
