spring:
  profiles:
    active: local
  resources:
    chain:
      compressed: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB
      file-size-threshold: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_MYAPP
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: shutdown
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
---
spring:
  profiles: local
  datasource:
    initialization-mode: always
    schema: classpath:/removabledb/schema.sql
    data: classpath:/removabledb/data.sql
    sql-script-encoding: UTF-8
server:
  port: 8080
variable:
  app:
    title: My SpringBoot + JPA + VueJs + Typescript
---
spring:
  profiles: dev
  datasource:
    hikari:
      username:
      password:
      driver-class-name: org.gjt.mm.mysql.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dbname?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull;
server:
  port: 8080
variable:
  app:
    title:
---
spring:
  profiles: production
  datasource:
    hikari:
      username:
      password:
      driver-class-name: org.gjt.mm.mysql.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dbname?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&&zeroDateTimeBehavior=convertToNull;
server:
  port:
variable:
  app:
    title:
