spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB
      file-size-threshold: 0
  mvc:
    converters:
      preferred-json-mapper: gson
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  web:
    resources:
      chain:
        compressed: true
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    validate-on-migrate: false
mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  type-aliases-super-type: java.io.Serializable
  type-aliases-package: com.github.bestheroz
  config-location: classpath:mybatis-config.xml
server:
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_DEMO
    encoding:
      charset: UTF-8
      enabled: true
      force: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: shutdown
decorator:
  datasource:
    p6spy:
      logging: slf4j
      multiline: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
  h2:
    console:
      enabled: true
server:
  port: 8080
sentry:
  logging:
    enabled: false
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    enabled-by-default: false
environment:
  app:
    test: test
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
server:
  port: 8080
sentry:
  dsn: https://7bb0a4fc0ddc4803998ee772401e3cfc@o368486.ingest.sentry.io/5197118
  environment: dev
  server-name:
  enable-tracing: true
  traces-sample-rate: 1.0
environment:
  app:
    test: test
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
server:
  port: 8000
sentry:
  dsn: https://7bb0a4fc0ddc4803998ee772401e3cfc@o368486.ingest.sentry.io/5197118
  environment: production
  server-name:
  enable-tracing: true
  traces-sample-rate: 1.0
environment:
  app:
    test: test
