version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build-and-deploy:
    working_directory: ~/circleci
    docker:
      - image: 'bestheroz/jdk8-maven-node-lastest'
    steps:
      - checkout
      - restore_cache:
          key: pom-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: pom-{{ checksum "pom.xml" }}
      - run: mvn clean
      - restore_cache:
          key: npm-packages-{{ checksum "vue/package.json" }}
      - run:
          name: npm install
          command: |
            cd vue;
            npm install;
      - save_cache:
          paths:
            - ~/circleci/vue/node_modules
          key: npm-packages-{{ checksum "vue/package.json" }}
      - run:
          name: npm lint && build
          command: |
            cd vue;
            npm run lint;
            npm run build;
      - run:
          name: move front-end dist to target
          command: |
            mkdir ~/circleci/target
            mkdir ~/circleci/target/classes
            mkdir ~/circleci/target/classes/static
            mv -f ~/circleci/vue/dist/* ~/circleci/target/classes/static/
      - run: mvn package -Dmaven.test.skip=true -Dspring.profiles.active=dev
      - run:
          name: Send Via SFTP
          command: |
            cd target;
            ls -l;
            lftp -u $username,''$password'' $hostname -e "bash /home/$project_name/WAS/bin/wasctl stop; sleep 5; cd /home/$project_name/WAS; put ./$project_name-1.jar; bash /home/$project_name/WAS/bin/wasctl start; quit";

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
                - /RC\/.*/
