CREATE TABLE SAMPLE_MEMBER_MST
(
    ID      VARCHAR(100) PRIMARY KEY NOT NULL,
    PASSWORD      CHAR(128)                NOT NULL,
    name    VARCHAR(100)             NOT NULL,
    MEMBER_TYPE    VARCHAR(100)             NOT NULL,
    LOGIN_FAIL_CNT INT(1) DEFAULT 0         NOT NULL,
    IS_CLOSED       BOOLEAN                  NOT NULL,
    TOKEN          VARCHAR(200)             NULL,
    EXPIRED        DATETIME                 NOT NULL,
    CREATED_BY     VARCHAR(100)             NOT NULL,
    CREATED        DATETIME                 NOT NULL,
    UPDATED_BY     VARCHAR(100)             NOT NULL,
    UPDATED        DATETIME                 NOT NULL
);
CREATE TABLE SAMPLE_MENU_MST
(
    ID       INT(10) PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(1000) NOT NULL,
    TYPE     CHAR(1)       NOT NULL,
    PARENT_ID   INT(10)       NOT NULL,
    IS_USING        BOOLEAN       NOT NULL,
    POWER         INT(10)       NOT NULL,
    DISPLAY_ORDER INT(10)       NOT NULL,
    URL           VARCHAR(4000),
    REMARK1       VARCHAR(4000),
    CREATED_BY    VARCHAR(100)  NOT NULL,
    CREATED       DATETIME      NOT NULL,
    UPDATED_BY    VARCHAR(100)  NOT NULL,
    UPDATED       DATETIME      NOT NULL
);
CREATE TABLE SAMPLE_CODE_MST
(
    GROUP_CODE      VARCHAR(100) PRIMARY KEY NOT NULL,
    NAME VARCHAR(1000)            NOT NULL,
    REMARK1         VARCHAR(4000),
    CREATED_BY      VARCHAR(100)             NOT NULL,
    CREATED         DATETIME                 NOT NULL,
    UPDATED_BY      VARCHAR(100)             NOT NULL,
    UPDATED         DATETIME                 NOT NULL
);

CREATE TABLE SAMPLE_CODE_DET
(
    GROUP_CODE    VARCHAR(100)  NOT NULL,
    CODE          VARCHAR(100)  NOT NULL,
    NAME     VARCHAR(1000) NOT NULL,
    IS_USING        BOOLEAN       NOT NULL,
    DISPLAY_ORDER INT(10)       NOT NULL,
    REMARK1       VARCHAR(4000),
    CREATED_BY    VARCHAR(100)  NOT NULL,
    CREATED       DATETIME      NOT NULL,
    UPDATED_BY    VARCHAR(100)  NOT NULL,
    UPDATED       DATETIME      NOT NULL
);
