name: 'Build Gradle'
description: 'Build gradle'

runs:
  using: 'composite'
  steps:
    - run: |
        echo "gradle build"
        gradle build --exclude-task test -Dspring.profiles.active=dev
        cp build/resources/main/application.yml build/
      shell: bash
