name: Deploy

on:
  push:
    branches: [ main, RC/** ]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 14 ]
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@main

      - uses: ./.github/actions/clean

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node
        uses: actions/cache@main
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        run: |
          cd vue
          npm ci
        env:
          CI: true

      - uses: ./.github/actions/test

      - uses: ./.github/actions/build-node

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache Gradle
        uses: actions/cache@main
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: ./.github/actions/build-gradle
