# This is a basic workflow to help you get started with Actions

name: Develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm-install:
    name: 1. npm install & cache
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14 ]

    steps:
      - uses: actions/checkout@main


      - name: Cache node
        id: cache-node
        uses: actions/cache@main
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.cache-node.outputs.cache-hit != 'true'
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Cypress
        uses: actions/cache@main
        if: steps.cache-node.outputs.cache-hit != 'true'
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          cd vue
          npm ci
        env:
          CI: true

  maven-install:
    name: 2. maven install & cache
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 11 ]

    steps:
      - uses: actions/checkout@main

      - name: Cache Maven packages
        id: cache-maven
        uses: actions/cache@main
        with:
          path: ~/.m2
          key: ${{ runner.os }}-java-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK ${{ matrix.java-version }}
        if: steps.cache-maven.outputs.cache-hit != 'true'
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java-version }}

      - name: mvn install
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: |
          mvn clean
          mvn dependency:go-offline
          mvn install

  lint:
    name: 3. lint & tsc & build
    needs: [npm-install, maven-install]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14 ]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node
        uses: actions/cache@main
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm run lint
        run: |
          cd vue
          npm run lint

      - name: npm run tsc
        run: |
          cd vue
          npm run tsc

      - name: npm run build
        run: |
          cd vue
          npm run build
