name: Test

on:
  push:
    branches-ignore: [ main, RC/** ]

jobs:
  npm-test:
    name: npm install & lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 14 ]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract version info
        id: version
        uses: ./.github/actions/parse-version

      - name: Cache node
        id: cache-node
        uses: actions/cache@main
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ steps.version.outputs.nodeVersion }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-${{ steps.version.outputs.nodeVersion }}-

      - name: npm install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          cd vue
          npm ci
        env:
          CI: true

      - uses: ./.github/actions/test
