# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm-install:
    name: 1. npm install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ubuntu-latest
        node-version: 14

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm install
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache Cypress
        id: cache-cypress
        uses: actions/cache@v2
        env:
          cache-name: cache-cypress
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          cd vue
          npm ci

      - name: npm run lint
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          cd vue
          npm lint

  maven-install:
    name: 2. maven install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ubuntu-latest
        java-version: 11

    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-m2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: mvn install
        run: |
          mvn clean
          mvn dependency:go-offline
          mvn install

  test:
    name: 3. build & run & test
    needs: [npm-install, maven-install]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ubuntu-latest
        node-version: 14
        java-version: 11

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm install
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache Cypress
        id: cache-cypress
        uses: actions/cache@v2
        env:
          cache-name: cache-cypress
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Cache Maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-m2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: npm run build
        run: |
          cd vue
          npm run build

      - name: move front-end dist to target
        run: |
          mkdir -p target/classes/static
          mv -f vue/dist/* target/classes/static/

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: mvn package
        run: |
          mvn package -Dmaven.test.skip=true -Dspring.profiles.active=dev

      - name: start server
        run: |
          cd target
          java -Dfile.encoding=UTF-8 -Xms2g -Xmx2g -XX:+UseG1GC -jar demo.jar &

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: vue
          start: npm run serve
          wait-on: 'http://localhost:8081'
          command-prefix: 'percy exec -- npx'
          command: npm run test

